import type { Metadata } from "next";
import "./globals.css";
import { JetBrains_Mono } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";
const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-mono", jetbrainsMono.variable)}>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono&display=swap"
          rel="stylesheet"
        />
        <link href="https://fonts.googleapis.com/css2?family=Bungee&display=swap" rel="stylesheet"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />
        <link href="https://api.fontshare.com/v2/css?f[]=satoshi@400,500,700&display=swap" rel="stylesheet"></link>
        <link href="https://api.fontshare.com/v2/css?f[]=clash-display@400,500,600,700&display=swap" rel="stylesheet"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Anton&family=Space+Grotesk:wght@300;400;500;700&display=swap" rel="stylesheet"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bowlby+One&display=swap"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet"></link>
      </head>
      <body
        className={`antialiased relative min-h-screen`}
          >              
<>
  {/* Side lines */}
  <div className="fixed left-[12%] top-0 h-full w-px bg-stone-200" />
  <div className="fixed right-[12%] top-0 h-full w-px bg-stone-200" />

  {/* Left label */}
  <div className="fixed left-6 top-1/2 -translate-y-1/2 -rotate-90 text-xs tracking-[0.6em] text-stone-400">
    ARCHITECTURE
  </div>

  {/* Right dots */}
  <div className="fixed right-0 top-0 h-full w-48 opacity-20">
    <div className="h-full bg-[radial-gradient(#999_1px,transparent_1px)] [background-size:24px_24px]" />
  </div>
  <div
  className="fixed inset-0 -z-10 opacity-5"
  style={{
    backgroundImage: "url('/Archi_Logo.png')",
    backgroundRepeat: "repeat",
    backgroundSize: "18px 18px",
    backgroundPosition: "0 0",
  }}
/>
</>
              <main>
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
          </ThemeProvider>
              </main>
      </body>
    </html>
  );
}


// bg-[#121316]